CNF-11184: remove seed image even if it is not mounted
openshift-kni/lifecycle-agent pull request #285
Opened 2024-02-06 05:22 UTC by sudomakeinstall2

Remove seed image even if it is not mounted as part of `UnmountAndRemoveImage`

2024-02-06 09:00 UTC, omertuc requested changes

2024-02-06 09:00 UTC, omertuc commented on lca-cli/ops/ops.go
> +	return o.removeImage(img)
Would this be equivalent?

```suggestion
	mounted, err := o.IsImageMounted(img)
	if err != nil {
		return fmt.Errorf("failed to check if image is mounted: %w", err)
	}

	if mounted {
		if _, err := o.hostCommandsExecutor.Execute(
			"podman", "image", "umount", img,
		); err != nil {
			return fmt.Errorf("failed to unmount image: %w", err)
		}
	}

	return o.removeImage(img)
```

2024-02-06 16:25 UTC, browsell commented
/lgtm

2024-02-08 13:55 UTC, jc-rh approved these changes

2024-02-08 14:12 UTC, donpenney commented
/override ci/prow/integration

2024-02-08 14:50 UTC, donpenney commented
/override ci/prow/integration

2024-02-08 15:02 UTC, merged