OCPBUGS-30190: Handle stale Backups during Upgrade stage
openshift-kni/lifecycle-agent pull request #403
Opened 2024-03-18 09:46 UTC by leo8a

If the target cluster is reinstalled before cleaning up any previous `Backups` from the object storage, OADP may sync those stale `Backup` CRs back to this cluster, even though they are labeled with a different `clusterID`.

This piece handles those stale backups during the `Upgrade` phase, basically we added a check to use only those `Backup` / `Restore` resources that matches the `clusterID` of the target cluster. Additionally, we also incorporated the `CleanupStaleBackups` function during this stage (for the case when any `Backup` is arbitrarily / unexpectedly changed between `Prep` and `Upgrade` stages).

Signed-off-by: Leonardo Ochoa-Aday [lochoa@redhat.com](mailto:lochoa@redhat.com)

/cc @Missxiaoguo @jc-rh @browsell

2024-03-18 09:47 UTC, leo8a commented
/hold

waiting for #402 to be merged first

2024-03-19 15:27 UTC, leo8a commented
rebased code, PTAL

2024-03-20 20:18 UTC, browsell commented
/test integration

2024-03-20 20:21 UTC, browsell commented
/lgtm

2024-03-25 21:58 UTC, Missxiaoguo requested changes

2024-03-25 21:58 UTC, Missxiaoguo commented on controllers/upgrade_handlers.go
> +		if allStaleBackupsRemoved, err := u.BackupRestore.CleanupStaleBackups(ctx, backups); err != nil {
The function CleanupStaleBackups was changed in [PR404](https://github.com/openshift-kni/lifecycle-agent/pull/404/files) to return only one variable.

2024-04-01 09:48 UTC, leo8a commented
code rebased, PTAL

2024-04-01 16:37 UTC, Missxiaoguo commented
/lgtm

2024-04-01 16:44 UTC, browsell commented
/approve

2024-04-01 16:47 UTC, merged